--- @meta

--- @class block
--- @field id number Block id
--- @field name string Block name like "block.minecraft.lever"
--- @field type string Block type
--- @field hardness number
--- @field blast_resistance number
--- @field is_solid boolean
--- @field is_liquid boolean
--- @field is_air boolean
--- @field age number? Crop age (only for crop blocks)
--- @field delay number? Repeater delay (only for repeaters)
--- @field locked boolean? Check if repeater locked (only for repeaters)
--- @field power number? Redstone wire power (only for redstone blocks)
--- @field facing direction? Block direction (only for directional blocks)
--- @field face string? Block face (only for walled blocks)
--- @field lit boolean? Check if redstone torch lit (only for redstone torch)
--- @field mode string? Comporator mode (only for comporator)
--- @field extended boolean? Check if piston extended (only for pistons)
--- @field layers number? Get count snow layers (only for snow layer)
--- @field is_still boolean? Check if block water logged (only for water and water logged blocks)
