--- @meta

--- @class effect
--- @field type string
--- @field duration number
--- @field amplifier number

--- @class entity
--- @field id string Entity id
--- @field uuid string Entity uuid
--- @field name string Entity name
--- @field display_name string Entity formatted name
--- @field is_alive boolean Check entity health > 0
--- @field is_child boolean Check entity is child
--- @field is_baby boolean Check entity is child
--- @field type boolean Entity type like "entity.minecraft.cow"
--- @field x number Entity position x
--- @field y number Entity position y
--- @field z number Entity position z
--- @field gravity number Entity gravity
--- @field horizontal_collision boolean Entity is touch horizontal block
--- @field vertical_collision boolean Entity is touch vertical block
--- @field controlled_venicle entity? Entity used boat or minecart
--- @field pos vector3d Entity position
--- @field position vector3d Entity position
--- @field box box Entity box
--- @field velocity_x number Entity x velocity
--- @field velocity_y number Entity y velocity
--- @field velocity_z number Entity z velocity
--- @field velocity vector3d Entity velocity
--- @field width number Entity width
--- @field height number Entity height
--- @field yaw number Entity yaw rotation
--- @field pitch number Entity pitch rotation
--- @field age number Entity age time
--- @field is_on_ground boolean Check entity is on ground
--- @field is_touching_water boolean Check entity is touching water
--- @field is_in_lava boolean Check entity is touching lava
--- @field is_sneaking boolean Check entity is sneaking
--- @field is_sprinting boolean Check entity is sprinting
--- @field is_swimming boolean Check entity is swimming
--- @field is_crouching boolean Check entity is crouching
--- @field passengers entity[] Drivers
--- @field distance_to_player number Distance to local player
--- @field item item? Item for ItemFrames and ItemEntity
--- @field health number? Entity health
--- @field max_health number? Entity maximum health
--- @field skin string? Player skin texture
--- @field main_hand item? Get an item in main hand
--- @field off_hand item? Get an item in off hand
--- @field head item? Get an item in head slot
--- @field chest item? Get an item in chestplate slot
--- @field legs item? Get an item in leggins slot
--- @field feet item? Get an item in feet slot
--- @field active_effects effect[]? Get entity potion effects
--- @field nbt string Get entity nbt
