--- @meta

--- @class enchantments
--- @field name string -- Enchantment name
--- @field level number -- Enchantment level

--- @class item
--- @field blockstate block? Block data
--- @field id integer Item id
--- @field count number Item count
--- @field max_count number Item maximum count
--- @field name string Item name
--- @field display_name string Item formatted name
--- @field is_empty boolean Check if item is empty
--- @field head_texture string? Return string if item its head and this has texture
--- @field skyblock_id string? Return string if has Hypixel SkyBlock Id
--- @field neu_id string? Return string if has NotEgnoughtUpdates Id
--- @field reforge_modifier string? Return string item has reforge on Hypixel SkyBlock
--- @field is_stackable boolean Check if item stackable
--- @field is_recombobulated boolean Check if item recombobulated on Hypixel SkyBlock
--- @field is_museum_donated boolean Check if item donated to museum on Hypixel SkyBlock
--- @field is_enchanted boolean Check if item has glinth effect
--- @field uuid string Item uuid on Hypixel SkyBlock
--- @field map map? Data for working with the “Map” subject
--- @field lore string[] Item lore
--- @field enchantments enchantments[] Item enchantments
--- @field hypixel_enchantments enchantments[] Hypixel SkyBlock Item enchantments
--- @field nbt string Item nbt
--- @field is_sword boolean Check if Item is sword
--- @field is_pickaxe boolean Check if Item is pickaxe
--- @field is_axe boolean Check if Item is axe
--- @field is_hoe boolean Check if Item is hoe
--- @field is_shovel boolean Check if Item is shovel
--- @field is_map boolean Check if Item is map
--- @field is_trident boolean Check if Item is trident
--- @field is_instrument boolean Check if Item is instrument
--- @field is_shield boolean Check if Item is shield
--- @field is_shears boolean Check if Item is shears
--- @field is_mace boolean Check if Item is mace
--- @field is_fishing_rod boolean Check if Item is fishing rod
--- @field is_block boolean Check if Item is block
