--- @meta

--- @class effect
--- @field type string
--- @field duration number
--- @field amplifier number

--- @class entity
--- @field id string Entity id
--- @field uuid string Entity uuid
--- @field name string Entity name
--- @field identifier string Block translation id like "minecraft:cow"
--- @field display_name string Entity formatted name
--- @field is_alive boolean Check entity health > 0
--- @field is_child boolean Check entity is child
--- @field is_baby boolean Check entity is child
--- @field type string Entity type like "entity.minecraft.cow"
--- @field x number Entity position x
--- @field y number Entity position y
--- @field z number Entity position z
--- @field gravity number Entity gravity
--- @field horizontal_collision boolean Entity is touch horizontal block
--- @field vertical_collision boolean Entity is touch vertical block
--- @field controlled_venicle entity? Entity used boat or minecart
--- @field pos vector3d Entity position
--- @field position vector3d Entity position
--- @field box box Entity box
--- @field velocity_x number Entity x velocity
--- @field velocity_y number Entity y velocity
--- @field velocity_z number Entity z velocity
--- @field velocity vector3d Entity velocity
--- @field width number Entity width
--- @field height number Entity height
--- @field yaw number Entity yaw rotation
--- @field pitch number Entity pitch rotation
--- @field age number Entity age time
--- @field is_on_ground boolean Check entity is on ground
--- @field is_touching_water boolean Check entity is touching water
--- @field is_in_lava boolean Check entity is touching lava
--- @field is_sneaking boolean Check entity is sneaking
--- @field is_sprinting boolean Check entity is sprinting
--- @field is_swimming boolean Check entity is swimming
--- @field is_crouching boolean Check entity is crouching
--- @field passengers entity[] Drivers
--- @field distance_to_player number Distance to local player
--- @field item item? Item for ItemFrames and ItemEntity
--- @field health number? Entity health
--- @field max_health number? Entity maximum health
--- @field skin string? Player skin texture
--- @field main_hand item? Get an item in main hand
--- @field off_hand item? Get an item in off hand
--- @field head item? Get an item in head slot
--- @field chest item? Get an item in chestplate slot
--- @field legs item? Get an item in leggins slot
--- @field feet item? Get an item in feet slot
--- @field active_effects effect[]? Get entity potion effects
--- @field inventory container? Player inventory (Player entities only)
--- @field is_invisible boolean Entity invisibility state (writable)
--- @field invisible boolean Alias for is_invisible (writable)
--- @field small boolean? ArmorStand small model (writable, ArmorStand only)
--- @field marker boolean? ArmorStand marker mode: no hitbox and no interaction (writable, ArmorStand only)
--- @field show_arms boolean? ArmorStand arms visibility (writable, ArmorStand only)
--- @field no_base_plate boolean? ArmorStand base plate visibility (writable, ArmorStand only)
--- @field no_baseplate boolean? Alias for no_base_plate
--- @field head_pose rotation3? ArmorStand head pose rotations in degrees {x,y,z} (writable via table or vector3d, ArmorStand only)
--- @field body_pose rotation3? ArmorStand body pose rotations in degrees (ArmorStand only)
--- @field left_arm_pose rotation3? ArmorStand left arm pose rotations in degrees (ArmorStand only)
--- @field right_arm_pose rotation3? ArmorStand right arm pose rotations in degrees (ArmorStand only)
--- @field left_leg_pose rotation3? ArmorStand left leg pose rotations in degrees (ArmorStand only)
--- @field right_leg_pose rotation3? ArmorStand right leg pose rotations in degrees (ArmorStand only)
--- @field text string? TextDisplay formatted text (writable via string or component, TextDisplay only)
--- @field line_width integer? TextDisplay maximum line width in pixels (writable, TextDisplay only)
--- @field text_opacity integer? TextDisplay text opacity 0-255 (writable, TextDisplay only)
--- @field background_color integer? TextDisplay ARGB background color (writable, TextDisplay only)
--- @field display_item item? ItemDisplay displayed item stack (writable, ItemDisplay only)
--- @field displayed_item item? Alias for display_item
--- @field interaction_width number? Interaction hitbox width, min 0 (writable, Interaction only)
--- @field interaction_height number? Interaction hitbox height, min 0 (writable, Interaction only)
--- @field response boolean? Interaction signals a successful interaction when true (writable, Interaction only)
--- @field display_block block? BlockDisplay displayed block state (writable, BlockDisplay only)
--- @field displayed_block block? Alias for display_block
--- @field billboard string? Display billboard mode (writable, Display only). Values:
---   - "fixed": no rotation, keeps its original orientation (default)
---   - "vertical": turns left/right to face the player
---   - "horizontal": tilts up/down to face the player
---   - "center": always fully faces the player's view
--- @field billboard_mode string? Alias for billboard
--- @field view_range number? Display visibility distance multiplier, min 0 (writable, Display only)
--- @field shadow_radius number? Display shadow radius, min 0 (writable, Display only)
--- @field shadow_strength number? Display shadow strength 0-1 (writable, Display only)
--- @field brightness_override integer? Display packed light override, -1 disables (writable, Display only)
--- @field transformation transform? Display translation/scale/rotation (writable via transform or raw Transformation userdata, Display only)
--- @field transform transform? Alias for transformation
--- @field nbt string Get entity nbt
--- @field blockpos blockpos Get entity block position
local entity = {}

--- Add a potion effect to the entity (LivingEntity only)
--- @param id string Effect identifier like "minecraft:speed", namespace can be omitted
--- @param duration integer? Duration in ticks, -1 for infinite (default -1)
--- @param amplifier integer? Amplifier level (default 0)
--- @return boolean applied
function entity.add_effect(id, duration, amplifier) end

--- Remove a potion effect from the entity, or all effects if id is omitted (LivingEntity only)
--- @param id string? Effect identifier to remove
--- @return boolean success
function entity.remove_effect(id) end

--- Teleport entity to a position work only for local player
--- @param x number
--- @param y number
--- @param z number
--- @param on_ground boolean
--- @return boolean status
--- @overload fun(pos: vector3d, on_ground: boolean): boolean
function entity.teleport(x, y, z, on_ground) end

--- @class rotation3
--- @field x number Rotation X in degrees
--- @field y number Rotation Y in degrees
--- @field z number Rotation Z in degrees
